jobs:
  build:
    docker:
    - image: cimg/openjdk:8.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - m2-repo-{{ checksum "pom.xml" }}
    - run: mvn clean package
  test:
    docker:
    - image: cimg/openjdk:8.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - m2-repo-{{ checksum "pom.xml" }}
    - run: mvn test
    - save_cache:
        key: m2-repo-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
orbs:
  maven: circleci/maven@1.0.0
version: 2.1
workflows:
  build_and_test:
    jobs:
    - test
    - build:
        requires:
        - test
  version: 2
