version: 2.1
orbs:
  maven: circleci/maven@1.0.0
jobs:
  test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-repo-{{ checksum "pom.xml" }}
      - run: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: m2-repo-{{ checksum "pom.xml" }}
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-repo-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/*.jar
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
